from typing import Sequence, overload
import numpy as np
from numpy.typing import ArrayLike, NDArray

class Link:
    @property
    def init(self) -> int: ...
    @property
    def term(self) -> int: ...
    @property
    def type(self) -> int: ...
    @property
    def length(self) -> float: ...
    @property
    def free_flow_time(self) -> float: ...
    @property
    def b(self) -> float: ...
    @property
    def power(self) -> float: ...
    @property
    def speed(self) -> float: ...
    @property
    def toll(self) -> float: ...
    capacity: float
    flow: float
    def delay(self, flow: float = -1.0) -> float: ...

class Network:
    @property
    def name(self) -> str: ...
    @property
    def number_of_nodes(self) -> int: ...
    @property
    def number_of_links(self) -> int: ...
    @property
    def number_of_zones(self) -> int: ...
    @property
    def number_of_od_pairs(self) -> int: ...
    def total_travel_time(self) -> float: ...
    def beckmann_objective(self) -> float: ...
    def relative_gap(self) -> float: ...
    def reset(self) -> None: ...
    def link(self, index: int) -> Link: ...
    def capacities(self) -> NDArray[np.float64]: ...
    def flows(self) -> NDArray[np.float64]: ...
    def free_flow_times(self) -> NDArray[np.float64]: ...
    def link_costs(self) -> NDArray[np.float64]: ...
    def link_nodes(self) -> NDArray[np.int64]: ...
    def set_capacities(self, capacities: ArrayLike) -> None: ...

class LinkConstraint:
    init_node: int
    term_node: int
    lower_bound: float
    upper_bound: float
    investment_cost_param: float
    def __init__(self, init_node: int, term_node: int, lower_bound: float,
                 upper_bound: float, investment_cost: float = 1.0) -> None: ...

class StepConfig:
    type: str
    name: str
    max_iterations: int
    tolerance: float
    algorithm: str
    local_algorithm: str
    local_max_iterations: int
    local_tolerance: float
    population_size: int
    step_size: float
    fd_epsilon: float
    gradient_method: str
    stochastic_optimizer: str
    def __init__(self) -> None: ...

class MetricsConfig:
    enable_trace: bool
    enable_relative_gap: bool
    relative_gap_sample_period: int
    flush_every_n_points: int
    write_metadata_json: bool
    write_summary_csv: bool
    append_dataset_subdir: bool
    output_root: str
    run_id: str
    scenario_name: str
    def __init__(self) -> None: ...

class TapOptions:
    approach: str
    relative_gap_tolerance: float
    max_iterations: int
    mu: float
    v: float
    shift_method: str
    route_search_threads: int
    full_iteration_count: int
    origin_iteration_count: int
    ema_alpha: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: TapOptions) -> None: ...

class CndpOptions:
    link_capacity_selection_threshold: float
    budget_threshold: float
    budget_function_multiplier: float
    budget_upper_bound: float
    route_search_threads: int
    exclude_insensitive_links: bool
    statistics_enabled: bool
    final_diagnostics: bool
    verbose: bool
    progress_format: str
    metrics: MetricsConfig
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: CndpOptions) -> None: ...

class TrafficAssignmentApproach:
    @property
    def approach_name(self) -> str: ...
    @property
    def network(self) -> Network: ...
    def compute_traffic_flows(self, statistics_recording: bool = False) -> None: ...
    def reset(self) -> None: ...
    def set_output_root(self, path: str) -> None: ...
    def set_route_search_threads(self, thread_count: int) -> None: ...

class TapasApproach(TrafficAssignmentApproach):
    def __init__(self, network: Network, alpha: float = 1e-14,
                 max_iterations: int = 200, mu: float = 0.5, v: float = 0.25) -> None: ...

class RouteBasedApproach(TrafficAssignmentApproach):
    def __init__(self, network: Network, alpha: float = 1e-14,
                 shift_method: str = "NewtonStep", route_search_threads: int = 1,
                 max_iterations: int = 200, full_iteration_count: int = 3,
                 origin_iteration_count: int = 1, ema_alpha: float = 0.7) -> None: ...

class NativeTapResult:
    @property
    def approach(self) -> str: ...
    @property
    def network_name(self) -> str: ...
    @property
    def relative_gap(self) -> float: ...
    @property
    def total_travel_time(self) -> float: ...
    @property
    def beckmann_objective(self) -> float: ...
    @property
    def flows(self) -> NDArray[np.float64]: ...
    @property
    def link_costs(self) -> NDArray[np.float64]: ...
    @property
    def solve_seconds(self) -> float: ...

class NativeCndpResult:
    @property
    def objective(self) -> float: ...
    @property
    def total_travel_time(self) -> float: ...
    @property
    def budget(self) -> float: ...
    @property
    def budget_upper_bound(self) -> float: ...
    @property
    def capacities(self) -> NDArray[np.float64]: ...
    @property
    def flows(self) -> NDArray[np.float64]: ...
    @property
    def lower_bounds(self) -> NDArray[np.float64]: ...
    @property
    def upper_bounds(self) -> NDArray[np.float64]: ...
    @property
    def elapsed_seconds(self) -> float: ...

class BilevelCND:
    @overload
    def __init__(self, network: Network, approach: TrafficAssignmentApproach,
                 constraints: Sequence[LinkConstraint], pipeline: Sequence[StepConfig],
                 options: CndpOptions) -> None: ...
    @overload
    def __init__(self, network: Network, approach: TrafficAssignmentApproach,
                 constraints: Sequence[LinkConstraint], pipeline: Sequence[StepConfig],
                 link_capacity_selection_threshold: float = 1e-3,
                 budget_threshold: float = 0.1, budget_function_multiplier: float = 5.0,
                 budget_upper_bound: float = 100000.0, metrics: MetricsConfig = ...,
                 route_search_threads: int = 1, progress_format: str = "none") -> None: ...
    def set_verbose(self, verbose: bool) -> None: ...
    def set_statistics_enabled(self, enabled: bool) -> None: ...
    def set_final_diagnostics_enabled(self, enabled: bool) -> None: ...
    def set_route_search_threads(self, thread_count: int) -> None: ...
    @property
    def active_constraint_count(self) -> int: ...
    def compute_network_design(self) -> NativeCndpResult: ...

def _make_approach(network: Network, options: TapOptions) -> TrafficAssignmentApproach: ...
def _solve_tap(approach: TrafficAssignmentApproach, reset: bool = False,
               statistics_recording: bool = False) -> NativeTapResult: ...
def _build_network_from_dataset(dataset: str, data_root: str) -> Network: ...
def _load_constraints(path: str, verbose: bool = False) -> list[LinkConstraint]: ...
def _build_network_from_arrays(name: str, n_nodes: int, n_zones: int,
                               init_node: ArrayLike, term_node: ArrayLike,
                               capacity: ArrayLike, length: ArrayLike,
                               free_flow_time: ArrayLike, b: ArrayLike, power: ArrayLike,
                               speed: ArrayLike, toll: ArrayLike, link_type: ArrayLike,
                               demand: ArrayLike) -> Network: ...
